image: solr:latest

install:
  stage: build
  script:
    - apt -y update && apt -y upgrade && apt install git mariadb-server python3 make && service mysql start
    - git clone -b init https://gitlab.dkrz.de/freva/deployment.git /tmp/deployment
    - sudo -E -u solr /opt/solr/bin/solr create_core -c latest -d example/files/conf
    - sudo -E -u solr /opt/solr/bin/solr create_core -c files -d example/files/conf
    - sudo -E -u solr cp /tmp/deployment/config/managed-schema /var/solr/data/latest/conf/managed-schema
    - sudo -E -u solr cp /tmp/deployment/config/managed-schema /var/solr/data/files/conf/managed-schema
    - cp evaluation_system.conf.tmpl evaluation_system.conf
    - python3 deploy /tmp/evaluation_system
    - mysql < src/evaluation_system/tests/mocks/create_user.sql
    - mysql -u test_user -pT3st -D freva_dev < /tmp/deployment/config/create_tables.sql
    - git config --global init.defaultBranch main
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"

unittest:
  stage: test
  script:
    # Do the unit tests
    - FREVA_ENV=/tmp/evaluation_system make tests
