stages:
    - build
    - test

dev-obs:
    stage: build
    image: 
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - if [ -n "$CI_COMMIT_BRANCH" ]; then IMAGETAG="$CI_COMMIT_BRANCH"; else IMAGETAG="$CI_COMMIT_SHA"; fi
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR
                       --reproducible
                       --cache
                       --skip-unused-stages=true
                       --build-arg=CI_REGISTRY_IMAGE=${CI_REGISTRY_IMAGE}
                       --build-arg=IMAGETAG=${IMAGETAG}
                       --whitelist-var-run=false
                       --dockerfile $CI_PROJECT_DIR/.docker/Dockerfile
                       --destination $CI_REGISTRY_IMAGE/freva_build:$CI_COMMIT_BRANCH
    tags:
        - docker, specific
    rules:
        - if: "$CI_COMMIT_BRANCH == 'master'"
        - if: "$CI_COMMIT_BRANCH != 'master'"

test39:

    stage: test
    image: registry.gitlab.dkrz.de/freva/evaluation_system/freva_build:$CI_COMMIT_BRANCH
    tags:
      - docker, specific
    before_script:
      - cp /tmp/evaluation_system/evaluation_system.conf .
    script:
        # Do the unit tests
      - python3 deploy.py /tmp/freva_39 --python=3.9 --run_tests
    artifacts:
      when: always
      reports:
        junit: report.xml

pages:
  stage: build
  dependencies:
    - test39
  artifacts:
    paths:
      - public/
