stages:
    - build
    - test

dev-obs:
    stage: build
    image: 
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - if [ -n "$CI_COMMIT_BRANCH" ]; then IMAGETAG="$CI_COMMIT_BRANCH"; else IMAGETAG="$CI_COMMIT_SHA"; fi
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR
                       --reproducible
                       --cache
                       --skip-unused-stages=true
                       --build-arg=CI_REGISTRY_IMAGE=${CI_REGISTRY_IMAGE}
                       --build-arg=IMAGETAG=${IMAGETAG}
                       --whitelist-var-run=false
                       --dockerfile $CI_PROJECT_DIR/.docker/Dockerfile
                       --destination $CI_REGISTRY_IMAGE/freva_build:$IMAGETAG
    tags:
        - docker, specific
    rules:
        - if: "$CI_COMMIT_BRANCH == 'master'"
        - if: "$CI_COMMIT_BRANCH != 'master'"

unittest:
    stage: test
    tags:
        - docker, specific
    script:
        # Do the unit tests
        - cd $CI_PROJECT_DIR; python3 deploy.py /tmp/evaluation_test
        - FREVA_ENV=/tmp/evaluation_system_test make tests

