name: freva-dev
channels:
  - conda-forge
dependencies:
  - python
  - conda
  - cartopy
  - ipython
  - mamba
  - pint
  - pip
  - mysql-common==8.3.0
  - mysql-libs=8.3.0
  - mysqlclient
  - pip:
      - dask==2024.8.0
      - -e .[test]
  - freva
  - pytest
  - pytest-env
  - pytest-cov
  - pytest-html
