name: freva-dev
channels:
  - conda-forge
dependencies:
  - python
  - conda
  - cartopy
  - ipython
  - mamba
  - pint
  - pip
  - pip:
      - -e .[test]
  - freva
  - pytest
  - pytest-env
  - pytest-cov
  - pytest-html
