name: freva-dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cdo
  - conda
  - configparser
  - distributed
  - django
  - ffmpeg
  - git
  - gitpython
  - dask
  - ipython
  - imagemagick
  - libnetcdf
  - humanize
  - mamba
  - mysqlclient
  - nco
  - netcdf4
  - numpy
  - pandas
  - pandoc
  - pint
  - pip
  - pip:
      - allure-pytest
      - requests_mock
      - pep257
      - types-requests
      - types-toml
      - humanize
  - pillow
  - pymysql
  - pypdf2
  - pytest
  - pytest-env
  - cartopy
  - pytest-cov
  - pytest-html
  - python-cdo
  - xarray
