name: freva-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - django
  - pytest-env
  - mysqlclient
  - nco
  - libnetcdf
  - dask
  - pip
  - pip:
      - allure-pytest
      - requests_mock
      - django-auth-ldap
      - django-datatable-view
      - django-templated-email
      - django_compressor
      - django-debug-toolbar-user-panel
      - django-discover-runner
      - django-bootstrap3
      - pep257
  - sphinx
  - pymysql
  - ipython
  - imagemagick
  - gitpython
  - git
  - conda
  - mamba
  - pillow
  - humanize
  - cartopy
  - python=3.9
  - numpy
  - ffmpeg
  - pytest-cov
  - pandoc
  - distributed
  - netcdf4
  - xarray
  - pytest
  - configparser
  - pandas
  - pytest-html
  - pypdf2
  - djangorestframework
  - python-memcached
  - scipy
  - django-debug-toolbar
  - paramiko
  - ldap3
  - django-nose
  - python-ldap
  - mock
  - pygtail
  - requests
  - toml
  - mod_wsgi
  - django-ipware
  - nose
  - nbval
  - h5netcdf
  - requests-mock
  - markdown
  - testpath
  - fabric
  - pylint
  - django-webpack-loader
  - django-model-utils
  - django-debug-toolbar
  - pep8
  - coverage
  - bleach
