name: freva-dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - conda
  - cartopy
  - ipython
  - mamba
  - pint
  - pip
  - freva
  - pytest
  - pytest-env
  - pytest-cov
  - pytest-html
