version: "3.9"
services:
  db:
    image: registry.gitlab.dkrz.de/freva/freva-service-config/freva-db:latest
    environment:
      MYSQL_USER: freva
      MYSQL_PASSWORD: T3st
      MYSQL_DATABASE: freva
      MYSQL_ROOT_PASSWORD: test_password_please_ignore
    ports:
      - "3306:3306"
  solr:
    image: registry.gitlab.dkrz.de/freva/freva-service-config/freva-solr:latest
    environment:
      CORE: files
    ports:
      - "8983:8983"
