version: "3.9"
services:
  db1:
    image: mariadb:latest
    environment:
      MYSQL_USER: freva
      MYSQL_PASSWORD: T3st
      MYSQL_DATABASE: freva
      MYSQL_ROOT_PASSWORD: test_password_please_ignore
    ports:
      - "3306:3306"
    volumes:
      - ./compose/config/mysql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql:ro
  db2:
    image: mariadb:latest
    environment:
      MYSQL_USER: freva
      MYSQL_PASSWORD: T3st
      MYSQL_DATABASE: freva
      MYSQL_ROOT_PASSWORD: test_password_please_ignore
    ports:
      - "3308:3306"
    volumes:
      - ./compose/config/mysql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql:ro
  solr:
    image: solr:latest
    environment:
      CORE: files
    ports:
      - "8983:8983"
    volumes:
      - ./compose/config/solr/managed-schema.xml:/opt/solr/managed-schema.xml:ro
      - ./compose/config/solr/create_cores.sh:/docker-entrypoint-initdb.d/create_cores.sh:ro
      - ./compose/config/solr/synonyms.txt:/opt/solr/synonyms.txt:ro
