version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    rebase-strategy: auto
    auto-merge: false
    target-branch: freva-dev
    reviewers:
      - "freva"
