#!/bin/bash
source_dir=$1

dump_file=/home/kadow/INTEGRATION/solr/incoming/$(date +solr_crawl_%F_%H%M%S.csv.gz)

if [[ ! -d "$source_dir" ]]; then
    echo "Directory '$source_dir' doesn't exists. Aborting."
    exit 1
fi

solr_ingest=/home/kadow/INTEGRATION/evaluation_system/sbin/solr_ingest

#create file (gzipped to something of about 10Mb)
$solr_ingest --crawl $source_dir --output $dump_file || exit 1
