#!/usr/bin/env python
# -*- coding: utf-8 -*-

from evaluation_system.misc import config
from myproxy.client import MyProxyClient
from evaluation_system.commands import BaseCommand

class EsgfCert(BaseCommand):
    _args=['help','debug']
    _short_args='hd'
    __short_description__='Get certificates from ESGF'
    
    outfile  = config.get('private_key')
    cadir    = config.get('cadir')
    hostname = config.get('esgf_host')
    port     = config.get('esgf_port')

    client_props = dict(caCertDir=cadir,
                        hostname=hostname,
                        port=port)
    
    def _run(self):
        myproxy = MyProxyClient(**self.client_props)
        credentials = myproxy.logon(config.get('esgf_user'), config.get('esgf_pass'), bootstrap=True, updateTrustRoots=True)

        fout = open(self.outfile, 'w')
        [fout.write(cred) for cred in credentials]
        fout.close()

if __name__ == "__main__":
    EsgfCert().run()
    
