#!/usr/bin/env python
# -*- coding: utf-8 -*-

from evaluation_system.misc import config
from evaluation_system.commands import BaseCommand, CommandError
from evaluation_system.fuse import EsgfFuse
from fuse import FUSE



class EsgfFS(BaseCommand):
    _args=['help','debug','foreground=','mountpoint=']
    _short_args='hd'
    __short_description__='Create a virtual ESGF filesystem'

    def _run(self):
        
        mountpoint = None
        foreground = True
        #parse arguments *!!!*
        for flag, arg in self.args:
            if    flag=='--mountpoint': mountpoint=arg #root path for ESGF (mandatory)
            elif  flag =='--foreground'     : foreground=arg #True for foreground, False for background
            
            
        if mountpoint is None: raise CommandError,'usage: ./esgf_fs --mountpoint=<root path for ESGF tempfile>'
        
        fuse = FUSE(EsgfFuse(), mountpoint, foreground=foreground, ro=True, fsname="ESGF_FS", nothreads=False,allow_other=True)    

        
if __name__ == "__main__":
    EsgfFS().run()    