#!/usr/bin/env python
# -*- coding: utf-8 -*-

from evaluation_system.misc import config
from evaluation_system.commands import BaseCommand, CommandError
from evaluation_system.fuse import Esgf2Solr

class EsgfCrawl(BaseCommand):
    _args=['help','debug','project=','experiment=','outpath=']
    _short_args='hd'
    __short_description__='Crawl the ESGF nodes'

    def _run(self):
        project    = None
        experiment = None
        outpath    = None
        
        #parse arguments *!!!*
        for flag, arg in self.args:
            if   flag =='--project'    : project=arg #ESGF Project (mandatory)
            elif flag =='--outpath'    : outpath=arg #Path for solr file (mandatory)
            elif flag =='--experiment' : experiment=arg #Limit to an experiment for ESGF search
        
        if project is None: raise CommandError,'Project was not given'
        if outpath is None: raise CommandError,'Outpath was not given'
        
        make_file = Esgf2Solr(project,experiment,outpath)
        make_file.find_experiment()
        make_file.get_path()
        

if __name__ == "__main__":
    EsgfCrawl().run()     
 