#!/bin/bash
#
#################
# Starts the Solr daemon via FREVA structure
#
# chkconfig: 345 90 10
# description: Starts the Solr daemon which will listen on port 8983
# 

# SET FREVA ROOT DIR via STRUCTURE
# This script (www_solr) is belonging to the sbin
#################
SCRIPT_PATH=$(readlink -f $(dirname $0))
FREVA_ROOT=$SCRIPT_PATH/../

# SET TOOL NAME OF YOUR SOLR SERVER
TOOL_NAME=mysolr
# SET THE USER WHICH RUNS THE SERVER (default: apache)
TOOL_USER=apache
# SET THE MEMORY OF THE SOLR SERVER (XXXXM for MB or XG for GB)
TOOL_MEM=4096M

BASE_DIR=$FREVA_ROOT/database/solr/server/$TOOL_NAME/
TOOL_HOME=$BASE_DIR/solr

PID_FILE=$BASE_DIR/var/$TOOL_NAME.pid
LOG_FILE=$BASE_DIR/log/$TOOL_NAME.log

TOOL_CMD="java -server -Xmx$TOOL_MEM -Djava.util.logging.config.file=$BASE_DIR/etc/logging.properties -Dsolr.solr.home=$TOOL_HOME -jar start.jar"


#CHECK IF RIGHT PATHES ARE SET
if [[ ! -f "$TOOL_HOME/solr.xml" ]]; then
    echo "WARNING: Can't find solr.xml in:"
    echo "$TOOL_HOME/"
    echo "Solr Server probably don't work"   
fi


case "$1" in
    start)
	if [[ ! -f "$PID_FILE" ]]; then
	    echo Starting $TOOL_NAME
	    #change max number of open files and start solr
	    # CHECK IF ulimit -n is important
  	    #su -p -s /bin/bash $TOOL_USER -c "ulimit -n 10000 && cd $BASE_DIR; nohup $TOOL_CMD >$LOG_FILE 2>&1 & echo \$!>$PID_FILE"
	    sudo -u $TOOL_USER /bin/bash -c "cd $BASE_DIR; nohup $TOOL_CMD >$LOG_FILE 2>&1 & echo \$!>$PID_FILE"
	    echo "Started. pid: $(cat $PID_FILE)"
	    #redhat specific
	    #touch /var/lock/subsys/$(basename $0)
	else
	    echo "$TOOL_NAME already runnin gwith pid $(cat $PID_FILE)"
	fi
	;;
    stop)
	if [[ -f "$PID_FILE" ]]; then
	    PID="$(cat "$PID_FILE")"
	    echo Stopping $TOOL_CMD: $PID
	    #kill $PID
	    #rm $PID_FILE
            sudo -u $TOOL_USER /bin/bash -c "kill $PID"
	    sudo -u $TOOL_USER /bin/bash -c "rm $PID_FILE"
	    #redhat specific
	    #rm -f /var/lock/subsys/$(basename $0)
	else
	    echo not started
	fi
	;;
    status)
	[[ -f "$PID_FILE" ]] && echo Running. pid:$(cat $PID_FILE) || echo Stopped
	;;
    *)
	echo "Usage: $0 {start|stop|status}"
	exit 1
	;;
esac

exit 0


