#!/bin/bash
#
#################
# Starts the Solr daemon via FREVA structure
#
# chkconfig: 345 90 10
# description: Starts the Solr daemon which will listen on port 8983
# 

# SET FREVA ROOT DIR via STRUCTURE
# This script (solr_server) is belonging to the sbin
#################
SCRIPT_PATH=$(readlink -f $(dirname $0))
FREVA_ROOT=$SCRIPT_PATH/../
IFS="=" read -r RAW_VAR SOLR_ROOT <<< "$(cat $FREVA_ROOT/etc/evaluation_system.conf | grep solr.root)"
# STRUCTURE FOR SOLR , READ FROM CONFIG
IFS="=" read -r RAW_VAR SERVER_DIR <<< "$(cat $FREVA_ROOT/etc/evaluation_system.conf | grep solr.server)"
IFS="=" read -r RAW_VAR INCOMING_DIR <<< "$(cat $FREVA_ROOT/etc/evaluation_system.conf | grep solr.incoming)"
IFS="=" read -r RAW_VAR PROCESSING_DIR <<< "$(cat $FREVA_ROOT/etc/evaluation_system.conf | grep solr.processing)"
IFS="=" read -r RAW_VAR BACKUP_DIR <<< "$(cat $FREVA_ROOT/etc/evaluation_system.conf | grep solr.backup)"

# SET TOOL NAME OF YOUR SOLR SERVER
IFS="=" read -r RAW_VAR TOOL_NAME <<< "$(cat $FREVA_ROOT/etc/evaluation_system.conf | grep solr.name)"
# SET THE USER WHICH RUNS THE SERVER (default: apache)
IFS="=" read -r RAW_VAR TOOL_USER <<< "$(cat $FREVA_ROOT/etc/evaluation_system.conf | grep solr.user)"
# SET THE MEMORY OF THE SOLR SERVER (XXXXM for MB or XG for GB)
IFS="=" read -r RAW_VAR TOOL_MEM <<< "$(cat $FREVA_ROOT/etc/evaluation_system.conf | grep solr.memory)"

# END OF CONFIG
################
BASE_DIR=$SERVER_DIR/$TOOL_NAME/
TOOL_HOME=$BASE_DIR/solr # dir where solr.xml file is located
# LOG AND PID
PID_FILE=$BASE_DIR/var/$TOOL_NAME.pid
LOG_FILE=$BASE_DIR/log/$TOOL_NAME.log
# THE SOLR SERVER RAWSTART COMMAND
TOOL_CMD="java -server -Xmx$TOOL_MEM -Djava.util.logging.config.file=$BASE_DIR/etc/logging.properties -Dsolr.solr.home=$TOOL_HOME -jar start.jar"
################
#CHECK IF RIGHT PATHES ARE SET (JUST POSSIBLE IN SAME FILE SYSTEM)
#if [[ ! -f "$TOOL_HOME/solr.xml" ]]; then
#    echo "WARNING: Can't find solr.xml in:"
#    echo "$TOOL_HOME/"
#    echo "Solr Server probably don't work"   
#fi
################
# SOLR_SERVER OPTIONS
case "$1" in
    start)
	if [[ ! -f "$PID_FILE" ]]; then
	    echo Starting $TOOL_NAME
	    sudo -u $TOOL_USER /bin/bash -c "cd $BASE_DIR; nohup $TOOL_CMD >$LOG_FILE 2>&1 & echo \$!>$PID_FILE"
	    echo "Started. pid: $(cat $PID_FILE)"
	else
	    echo "$TOOL_NAME already running with pid $(cat $PID_FILE)"
	fi
	;;
    stop)
	if [[ -f "$PID_FILE" ]]; then
	    PID="$(cat "$PID_FILE")"
	    echo Stopping $TOOL_CMD: $PID
	    sudo -u $TOOL_USER /bin/bash -c "kill $PID"
	    sudo -u $TOOL_USER /bin/bash -c "rm $PID_FILE"
	else
	    echo not started
	fi
	;;
    status)
	[[ -f "$PID_FILE" ]] && echo Running. pid:$(cat $PID_FILE) || echo Stopped
	;;
    check4break)
	if [[ ! -f "$PID_FILE" ]]; then
	    echo "SOLR is stopped, has no PID"
	    echo "START SOLR with start option"
	elif [[ -f "$PID_FILE" ]] && [[ -z  "$(ps -A | grep $(cat $PID_FILE))" ]]; then
	    echo "SOLR IS DOWN"
	    echo "BUT NOT BY THIS SCRIPT"
	    echo "-> RESTART"
            #STOP
	    PID="$(cat "$PID_FILE")"
	    sudo -u $TOOL_USER /bin/bash -c "rm $PID_FILE"
	    #WAIT FOR SOME SECONDS
	    sleep 5
	    #START
	    echo Restarting $TOOL_NAME
            sudo -u $TOOL_USER /bin/bash -c "cd $BASE_DIR; nohup $TOOL_CMD >$LOG_FILE 2>&1 & echo \$!>$PID_FILE"
            echo "Restarted. pid: $(cat $PID_FILE)"
	else
	    echo "$TOOL_NAME is running with pid $(cat $PID_FILE)"
 	fi
        ;;
    path2ingest)
	DATA_DIR=$2
	file=$(date +solr_crawl_%F_%H%M%S.csv.gz) # file to be filled with informations
	log_file=$BACKUP_DIR/$file.log
	exec > >(tee $log_file)
	exec 2>&1
        # LOAD MODULES e.g. FREVA itself for right environment, point to binary of solr_ingest
	module load evaluation_system 1>/dev/null 2>/dev/null
	SOLR_INGEST=$FREVA_ROOT/sbin/solr_ingest
	# CRAWL PART
	INCOMING_FILE=$INCOMING_DIR/$file
        [[ ! -d "$DATA_DIR" ]] && echo "Directory '$DATA_DIR' doesn't exists. Aborting." && exit 1
	$SOLR_INGEST --crawl $DATA_DIR --output $INCOMING_FILE || exit 1
	#INGEST PART
	PROCESSING_FILE=$PROCESSING_DIR/$file
	mv $INCOMING_FILE $PROCESSING_FILE || continue #if we can't assume the file is not there anymore.
	if $SOLR_INGEST --ingest "$PROCESSING_FILE"; then
	    echo "success"
	    mv $PROCESSING_FILE $BACKUP_DIR/$file
	else
	    echo "FAILURE!"
	    mv $PROCESSING_FILE $BACKUP_DIR/failed_$file
	fi
	;;    

    *)
	echo "Usage: $0 {start|stop|status|check4break|path2ingest <value>}"
	exit 1
	;;
esac

exit 0


