#!/bin/bash
#
#
# Starts the Solr daemon
#
# chkconfig: 345 90 10
# description: Starts the Solr daemon which will listen on port 8983

FREVA_ROOT=/pf/b/b324031/INTEGRATION/evaluation_system/

TOOL_NAME=mysolr
TOOL_USER=apache
BASE_DIR=$FREVA_ROOT/database/solr/server/$TOOL_NAME/
TOOL_HOME=$BASE_DIR/solr


PID_FILE=$BASE_DIR/var/$TOOL_NAME.pid
LOG_FILE=$BASE_DIR/log/$TOOL_NAME.log

TOOL_CMD="java -server -Xmx3072M -Djava.util.logging.config.file=$BASE_DIR/etc/logging.properties -Dsolr.solr.home=$TOOL_HOME -jar start.jar"


case "$1" in
    start)
	if [[ ! -f "$PID_FILE" ]]; then
	    echo Starting $TOOL_NAME
	    #change max number of open files and start solr
	    # CHECK IF ulimit -n is important
  	    #su -p -s /bin/bash $TOOL_USER -c "ulimit -n 10000 && cd $BASE_DIR; nohup $TOOL_CMD >$LOG_FILE 2>&1 & echo \$!>$PID_FILE"
	    sudo -u $TOOL_USER /bin/bash -c "cd $BASE_DIR; nohup $TOOL_CMD >$LOG_FILE 2>&1 & echo \$!>$PID_FILE"
	    echo "Started. pid: $(cat $PID_FILE)"
	    #redhat specific
	    #touch /var/lock/subsys/$(basename $0)
	else
	    echo "$TOOL_NAME already runnin gwith pid $(cat $PID_FILE)"
	fi
	;;
    stop)
	if [[ -f "$PID_FILE" ]]; then
	    PID="$(cat "$PID_FILE")"
	    echo Stopping $TOOL_CMD: $PID
	    sudo -u $TOOL_USER /bin/bash -c "kill $PID"
	    sudo -u $TOOL_USER /bin/bash -c "rm $PID_FILE"
	    #redhat specific
	    #rm -f /var/lock/subsys/$(basename $0)
	else
	    echo not started
	fi
	;;
    status)
	[[ -f "$PID_FILE" ]] && echo Running. pid:$(cat $PID_FILE) || echo Stopped
	;;
    *)
	echo "Usage: $0 {start|stop|status}"
	exit 1
	;;
esac

exit 0


