CREATE USER IF NOT EXISTS freva IDENTIFIED BY 'T3st';
CREATE DATABASE IF NOT EXISTS freva;
GRANT ALL PRIVILEGES ON freva.* TO 'freva'@'%' IDENTIFIED BY 'T3st';
GRANT ALL PRIVILEGES ON freva.* TO 'freva'@'localhost' IDENTIFIED BY 'T3st';
FLUSH PRIVILEGES;
