name: Creating container images
run-name: Creating container images 🧉

permissions:
  pull-requests: write
  contents: write
  packages: write

on:
  push:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    strategy:
      matrix:
        image-name: [freva-dev, freva]
        build-args: [binder=false, ""]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.X
        uses: actions/setup-python@v4
        with:
          python-version: "3.X"

      - name: Get tag
        id: repository
        run: |
          echo "tag=$(python src/evaluation_system/__init__.py)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.image-name }} image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          file: .docker/Dockerfile
          push: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/main' }}
          build-args:
            VERSION=${{ steps.repository.outputs.tag }}
            ${{ matrix.build-args }}
          tags: |
            ghcr.io/freva-clint/${{matrix.image-name}}:${{ steps.repository.outputs.tag }}
            ghcr.io/freva-clint/${{matrix.image-name}}:latest
