name: CI Tests
run-name: ${{ github.actor }} is testing the code

on:
  push:
    branches: [ master ]
  pull_request:


jobs:
  test:
    runs-on: antarcticrainforest/freva-dev
    env:
      CONDA_ENV: freva-dev
      NUMEXPR_MAX_THREADS: 8
      FREVA_ENV: /tmp/freva/bin
      EVALUATION_SYSTEM_CONFIG_FILE: .docker/evaluation_system.conf
      GIT_SUBMODULE_STRATEGY: recursive
    strategy:
        max-parallel: 5
        matrix:
          python-version: [3.7, 3.8, 3.9, "3.10"]
    steps:
    -
      name: Ceckout
      uses: actions/checkout@v3
    -
      name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.python-versoin}}
    -
      name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    -
      name: Creating conda python ${{ matrix.python-version }} env
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
      run: |
        python deploy.py /tmp/freva -e -s --packages xarray gitpython pandoc mysqlclient
    -
      name: Running tests for python ${{ matrix.python-version }}
      run: |
        make test_coverage
    -
      name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
