name: Linter
run-name: ${{ github.actor }} is linting the code

on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Ceckout
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install packages
      run: |
        python3 -m pip install -e .[test]
    - name: Linting
      run: make lint
