name: Create Pip package
run-name: ${{ github.actor }} is uploading the code to pypi

on:
  push:
    tags:
      - "*"

jobs:
  pipy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
